name = "jsandy-www"
main = ".open-next/worker.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
account_id = "9095722a1cb3e114ae640b422767d94a"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[limits]
cpu_ms = 30000

[observability]
enabled = true
head_sampling_rate = 1

[placement]
mode = "smart"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "jsandy-www"

[env.production]
name = "jsandy-www"

[env.production.vars]
SERVICE_NAME = "www"

[[env.production.r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "jsandy-www"
